<div class="admin-resource">
    <style>
        .ar-head{padding:1.4rem;border-radius:18px;background:linear-gradient(135deg,#2b6753,#43866f);color:#fff}.ar-card{border:1px solid #e4ebe8;border-radius:15px;box-shadow:0 4px 16px rgba(20,55,44,.05);overflow:hidden}.ar-label{font-size:.72rem;font-weight:600;letter-spacing:.05em;text-transform:uppercase;color:#708079}.ar-actions{white-space:nowrap}.ar-table{min-width:720px}.ar-table td{vertical-align:middle}
    </style>
    <header class="ar-head mb-4 d-flex justify-content-between align-items-center"><div><small>ADMIN WORKSPACE</small><h1 class="h3 mb-1">{{ $definition[0] }}</h1><p class="mb-0" style="opacity:.8">Manage {{ strtolower($definition[0]) }} without leaving this page.</p></div><button wire:click="create" class="btn btn-light"><i class="fas fa-plus mr-1"></i> Add</button></header>
    @if(session()->has('success'))<div class="alert alert-success">{{session('success')}}</div>@endif @if(session()->has('error'))<div class="alert alert-danger">{{session('error')}}</div>@endif
    @if($showForm)<form wire:submit.prevent="save" class="card ar-card mb-4"><div class="card-body"><div class="d-flex justify-content-between"><h2 class="h5">{{ $recordId?'Edit':'New' }} record</h2><button type="button" wire:click="resetForm" class="close">&times;</button></div><div class="row mt-3">
        @foreach($definition[3] as $field=>$label)<div class="form-group col-md-6"><label class="ar-label">{{ $label }}</label>
            @if($field==='section_id')<select wire:model.defer="form.{{$field}}" class="form-control"><option value="">All sections</option>@foreach($sections as $section)<option value="{{$section->id}}">{{$section->name}}</option>@endforeach</select>
            @elseif($field==='user_status')<select wire:model.defer="form.user_status" class="form-control"><option value="Active">Active</option><option value="Inactive">Inactive</option></select>
            @elseif($field==='state_id')<select wire:model="form.state_id" class="form-control"><option value="">Select state</option>@foreach($states as $state)<option value="{{$state->id}}">{{$state->name}}</option>@endforeach</select>
            @elseif($field==='lga_id')<select wire:model.defer="form.lga_id" class="form-control" @if(empty($form['state_id'])) disabled @endif><option value="">{{ empty($form['state_id']) ? 'Select state first' : 'Select LGA' }}</option>@foreach($lgas as $lga)<option value="{{$lga->id}}">{{$lga->name}}</option>@endforeach</select>
            @elseif($field==='lga_id')<select wire:model.defer="form.{{$field}}" class="form-control"><option value="">Select LGA</option>@foreach($lgas as $lga)<option value="{{$lga->id}}">{{$lga->name}}{{ $lga->state ? ' — '.$lga->state->name : '' }}</option>@endforeach</select>
            @elseif($field==='status')<select wire:model.defer="form.{{$field}}" class="form-control"><option>Active</option><option>Not Active</option></select>
            @elseif($field==='gender')<select wire:model.defer="form.{{$field}}" class="form-control"><option value="">Select</option><option value="1">Male</option><option value="2">Female</option></select>
            @elseif($field==='comment_type')<select wire:model.defer="form.{{$field}}" class="form-control"><option value="teacher">Teacher comment</option><option value="head">Head-teacher comment</option></select>
            @elseif($field==='password' || $field==='password_confirmation')<input wire:model.defer="form.{{$field}}" type="password" autocomplete="new-password" class="form-control">
            @elseif(strpos($field,'_at') !== false || $field==='date_of_birth')<input wire:model.defer="form.{{$field}}" type="date" class="form-control">
            @elseif($field==='address' || $field==='remark' || $field==='name' && $resource==='comments')<textarea wire:model.defer="form.{{$field}}" class="form-control" rows="2"></textarea>
            @else<input wire:model.defer="form.{{$field}}" class="form-control" type="{{ in_array($field,['level','duration','capacity','pass_mark','from','to'])?'number':'text' }}">@endif
            @error('form.'.$field)<small class="text-danger">{{$message}}</small>@enderror</div>@endforeach
    </div><button class="btn btn-success"><i class="fas fa-save mr-1"></i> Save</button><button type="button" wire:click="resetForm" class="btn btn-light">Cancel</button></div></form>@endif
    <div class="card ar-card"><div class="card-body border-bottom"><label class="ar-label">Live search</label><input wire:model.debounce.300ms="search" class="form-control" placeholder="Search records"></div><div class="table-responsive"><table class="table table-hover mb-0 ar-table"><thead class="thead-light"><tr>@foreach($definition[3] as $field=>$label) @if(!in_array($field,['comment_type','password','password_confirmation']))<th>{{$label}}</th>@endif @endforeach @if($resource==='comments')<th>Type</th>@endif<th class="text-right">Actions</th></tr></thead><tbody>
        @foreach($records as $record)<tr wire:key="record-{{$record->id}}">@foreach($definition[3] as $field=>$label) @if(!in_array($field,['comment_type','password','password_confirmation']))<td>@if($field==='user_name'){{optional($record->user)->name}}@elseif($field==='user_email'){{optional($record->user)->email}}@elseif($field==='lga_id'){{optional($record->lga)->name}}@elseif($field==='section_id'){{optional($sections->firstWhere('id',$record->$field))->name ?? 'All'}}@elseif($field==='gender'){{$record->$field==1?'Male':'Female'}}@else{{Str::limit($record->$field,60)}}@endif</td>@endif @endforeach @if($resource==='comments')<td><span class="badge badge-info">Teacher</span></td>@endif<td class="text-right ar-actions">@if($resource==='calendar')<button wire:click="manageTerms({{$record->id}})" class="btn btn-sm btn-outline-success"><i class="fas fa-calendar-week mr-1"></i>Terms</button>@endif <button wire:click="edit({{$record->id}}{{ $resource==='comments' ? ",'teacher'" : '' }})" class="btn btn-sm btn-outline-primary">Edit</button><button wire:click="delete({{$record->id}}{{ $resource==='comments' ? ",'teacher'" : '' }})" onclick="confirm('Delete this record?')||event.stopImmediatePropagation()" class="btn btn-sm btn-outline-danger">Delete</button></td></tr>@endforeach
        @if($resource==='comments')@foreach($headComments as $record)<tr wire:key="head-comment-{{$record->id}}"><td>{{Str::limit($record->name,60)}}</td><td>{{$record->gender==1?'Male':'Female'}}</td><td><span class="badge badge-secondary">Head teacher</span></td><td class="text-right ar-actions"><button wire:click="edit({{$record->id}},'head')" class="btn btn-sm btn-outline-primary">Edit</button><button wire:click="delete({{$record->id}},'head')" onclick="confirm('Delete this record?')||event.stopImmediatePropagation()" class="btn btn-sm btn-outline-danger">Delete</button></td></tr>@endforeach @endif
        @if($records->isEmpty() && $headComments->isEmpty())<tr><td colspan="10" class="text-center text-muted py-5">No records found.</td></tr>@endif
    </tbody></table></div>@if($records->hasPages())<div class="card-footer bg-white">{{$records->links()}}</div>@endif</div>

    @if($resource==='calendar' && $termSession)
        <section class="card ar-card mt-4" id="session-terms">
            <div class="card-header bg-white d-flex justify-content-between align-items-center"><div><span class="ar-label">Academic session terms</span><h2 class="h5 mb-0">{{$termSession->name}}</h2></div><button wire:click="createTerm" class="btn btn-success btn-sm"><i class="fas fa-plus mr-1"></i>Add term</button></div>
            @if($showTermForm)<form wire:submit.prevent="saveTerm" class="card-body border-bottom"><div class="form-row">
                <div class="form-group col-md-3"><label class="ar-label">Term</label><select wire:model.defer="termForm.term_id" class="form-control"><option value="">Select term</option>@foreach($terms as $term)<option value="{{$term->id}}">{{$term->name}}</option>@endforeach</select>@error('termForm.term_id')<small class="text-danger">{{$message}}</small>@enderror</div>
                <div class="form-group col-md-3"><label class="ar-label">Status</label><select wire:model.defer="termForm.status" class="form-control"><option>Not Active</option><option>Active</option></select>@error('termForm.status')<small class="text-danger">{{$message}}</small>@enderror</div>
                <div class="form-group col-md-3"><label class="ar-label">Starts</label><input type="date" wire:model.defer="termForm.start_at" class="form-control">@error('termForm.start_at')<small class="text-danger">{{$message}}</small>@enderror</div>
                <div class="form-group col-md-3"><label class="ar-label">Ends</label><input type="date" wire:model.defer="termForm.end_at" class="form-control">@error('termForm.end_at')<small class="text-danger">{{$message}}</small>@enderror</div>
            </div><button class="btn btn-success"><i class="fas fa-save mr-1"></i>Save term</button> <button type="button" wire:click="resetTermForm" class="btn btn-light">Cancel</button></form>@endif
            <div class="table-responsive"><table class="table table-hover mb-0"><thead class="thead-light"><tr><th>Term</th><th>Status</th><th>Starts</th><th>Ends</th><th class="text-right">Actions</th></tr></thead><tbody>
                @forelse($sessionTerms as $sessionTerm)<tr wire:key="session-term-{{$sessionTerm->id}}"><td>{{optional($sessionTerm->term)->name}}</td><td><span class="badge badge-{{$sessionTerm->status==='Active'?'success':'secondary'}}">{{$sessionTerm->status}}</span></td><td>{{$sessionTerm->start_at ?: '-'}}</td><td>{{$sessionTerm->end_at ?: '-'}}</td><td class="text-right"><button wire:click="editTerm({{$sessionTerm->id}})" class="btn btn-sm btn-outline-primary">Edit</button> <button wire:click="deleteTerm({{$sessionTerm->id}})" onclick="confirm('Delete this session term?')||event.stopImmediatePropagation()" class="btn btn-sm btn-outline-danger">Delete</button></td></tr>@empty<tr><td colspan="5" class="text-center text-muted py-4">No terms configured for this session.</td></tr>@endforelse
            </tbody></table></div>
        </section>
    @endif
</div>
