<div class="container-fluid py-3">
<h3>Fees Setting</h3><p class="text-muted">Configure fee categories for each class and term.</p>
@if(session('success'))<div class="alert alert-success">{{session('success')}}</div>@endif @if(session('error'))<div class="alert alert-danger">{{session('error')}}</div>@endif
<div class="card mb-3"><div class="card-body"><div class="form-row"><div class="col-md-5"><input wire:model.defer="categoryName" class="form-control" placeholder="New fee category"></div><div class="col-md-2"><button wire:click="addCategory" class="btn btn-outline-primary">Add category</button></div></div></div></div>
@if($showForm)<div class="card mb-3"><div class="card-body"><div class="form-row">
<div class="form-group col-md-3"><label>Section</label><select wire:model="sectionId" class="form-control"><option value="">Select</option>@foreach($sections as $v)<option value="{{$v->id}}">{{$v->name}}</option>@endforeach</select></div>
<div class="form-group col-md-3"><label>Class</label><select wire:model.defer="classId" class="form-control"><option value="">Select</option>@foreach($classes as $v)<option value="{{$v->id}}">{{$v->name}}</option>@endforeach</select></div>
<div class="form-group col-md-3"><label>Category</label><select wire:model.defer="feeId" class="form-control"><option value="">Select</option>@foreach($fees as $v)<option value="{{$v->id}}">{{$v->name}}</option>@endforeach</select></div>
<div class="form-group col-md-3"><label>Term</label><select wire:model.defer="termId" class="form-control"><option value="">Select</option>@foreach($terms as $v)<option value="{{$v->id}}">{{$v->name}}</option>@endforeach</select></div>
<div class="form-group col-md-3"><label>Gender (optional)</label><select wire:model.defer="genderId" class="form-control"><option value="">All</option>@foreach($genders as $v)<option value="{{$v->id}}">{{$v->name}}</option>@endforeach</select></div>
<div class="form-group col-md-3"><label>Amount</label><input type="number" wire:model.defer="amount" class="form-control"></div></div>
<button wire:click="save" class="btn btn-success">Save</button> <button wire:click="resetForm" class="btn btn-light">Cancel</button></div></div>@endif
<div class="card"><div class="card-header bg-white d-flex justify-content-between align-items-center"><strong>Class fees</strong><button wire:click="create" class="btn btn-primary btn-sm"><i class="fas fa-plus mr-1"></i>Add fee</button></div><div class="card-body">
<div class="form-row mb-3"><div class="col-md-4"><select wire:model="sectionId" class="form-control"><option value="">All sections</option>@foreach($sections as $v)<option value="{{$v->id}}">{{$v->name}}</option>@endforeach</select></div><div class="col-md-4"><select wire:model="classId" class="form-control"><option value="">All classes</option>@foreach($classes as $v)<option value="{{$v->id}}">{{$v->name}}</option>@endforeach</select></div></div>
<div class="table-responsive"><table class="table"><thead><tr><th>Class</th><th>Category</th><th>Term</th><th>Amount</th><th></th></tr></thead><tbody>@forelse($items as $item)<tr><td>{{$item->sectionClassFee->sectionClass->name}}</td><td>{{$item->sectionClassFee->fee->name}}</td><td>{{optional($item->term)->name}}</td><td>{{number_format($item->amount,2)}}</td><td><button wire:click="edit({{$item->id}})" class="btn btn-sm btn-outline-primary">Edit</button> <button wire:click="delete({{$item->id}})" class="btn btn-sm btn-outline-danger">Delete</button></td></tr>@empty<tr><td colspan="5" class="text-center">No fee settings.</td></tr>@endforelse</tbody></table></div></div></div></div>
