<div class="container-fluid py-3">
    @if(session()->has('success'))<div class="alert alert-success" role="status">{{ session('success') }}</div>@endif
    <div class="d-flex flex-wrap justify-content-between align-items-center mb-3"><div><h3 class="mb-1">Advance Payment Monitoring</h3><p class="text-muted mb-0">Track future payments from collection through class activation.</p></div></div>
    <div class="row mb-3"><div class="col-md-4 mb-2"><div class="card h-100 border-0 shadow-sm"><div class="card-body"><small class="text-muted">Advance collected</small><div class="h4 mb-0">{{number_format($summary['collected'],2)}}</div></div></div></div><div class="col-md-4 mb-2"><div class="card h-100 border-0 shadow-sm"><div class="card-body"><small class="text-muted">Applied to fees</small><div class="h4 mb-0 text-success">{{number_format($summary['applied'],2)}}</div></div></div></div><div class="col-md-4 mb-2"><div class="card h-100 border-0 shadow-sm"><div class="card-body"><small class="text-muted">Pending credit</small><div class="h4 mb-0 text-warning">{{number_format($summary['credit'],2)}}</div></div></div></div></div>
    <div class="card shadow-sm"><div class="card-body border-bottom"><div class="form-row">
        <div class="form-group col-md"><label>Student</label><input wire:model.debounce.300ms="search" class="form-control" placeholder="Name or admission number"></div>
        <div class="form-group col-md"><label>Session</label><select wire:model="academicSessionId" class="form-control"><option value="">All sessions</option>@foreach($sessions as $session)<option value="{{$session->id}}">{{$session->name}}</option>@endforeach</select></div>
        <div class="form-group col-md"><label>Section</label><select wire:model="sectionId" class="form-control"><option value="">All sections</option>@foreach($sections as $section)<option value="{{$section->id}}">{{$section->name}}</option>@endforeach</select></div>
        <div class="form-group col-md"><label>Class</label><select wire:model="classId" class="form-control"><option value="">All classes</option>@foreach($classes as $class)<option value="{{$class->id}}">{{$class->name}}</option>@endforeach</select></div>
        <div class="form-group col-md"><label>Status</label><select wire:model="status" class="form-control"><option value="">All statuses</option><option>Pending</option><option>Partially Applied</option><option>Applied</option><option>Cancelled</option><option>Refunded</option></select></div>
    </div></div>
    <div class="table-responsive"><table class="table table-hover mb-0"><thead class="thead-light"><tr><th>Student</th><th>Destination</th><th>Fee / term</th><th>Collected</th><th>Applied</th><th>Credit</th><th>Status</th><th></th></tr></thead><tbody>
        @forelse($records as $record)<tr><td>{{$record->student->name}}<br><small class="text-muted">{{$record->student->admission_no}}</small></td><td>{{$record->academicSession->name}}<br><small>{{optional($record->sectionClass->section)->name}} / {{$record->sectionClass->name}}</small></td><td>{{$record->fee->name}}<br><small>{{$record->term->name}}</small></td><td>{{number_format($record->amount,2)}}</td><td>{{number_format($record->applied_amount,2)}}</td><td>{{number_format($record->remaining_amount,2)}}</td><td><span class="badge badge-{{$record->status==='Applied'?'success':($record->status==='Pending'?'warning':'info')}}">{{$record->status}}</span></td><td><a target="_blank" href="{{route('finance.advance-payments.receipt',$record->id)}}" class="btn btn-sm btn-outline-primary"><i class="fas fa-print mr-1"></i>Receipt</a> <button type="button" wire:click="deleteAdvancePayment({{$record->id}})" wire:loading.attr="disabled" onclick="confirm('Delete this advance payment entry? Any amount applied to fees will be reversed. Other entries on this receipt will remain.') || event.stopImmediatePropagation()" class="btn btn-sm btn-outline-danger ml-1"><i class="fas fa-trash mr-1"></i>Delete</button></td></tr>@empty<tr><td colspan="8" class="text-center text-muted py-5">No advance payments match these filters.</td></tr>@endforelse
    </tbody></table></div>@if($records->hasPages())<div class="card-footer bg-white">{{$records->links()}}</div>@endif</div>
</div>
